version: '3.8'

services:
  vietlot-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5114:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=DESKTOP-S48P9OU;Database=DemoDB;User Id=;Password=;TrustServerCertificate=True;MultipleActiveResultSets=true
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=VietLot@Pass123!