// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VietLotApi.Data;

#nullable disable

namespace VietLotApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603040407_AddRoles")]
    partial class AddRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VietLotApi.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ColorCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "G001",
                            ColorCode = "#7c3aed",
                            CreatedAt = new DateTime(2026, 6, 3, 4, 4, 5, 371, DateTimeKind.Utc).AddTicks(2743),
                            Description = "Toan quyen he thong",
                            Name = "Admin (Giam doc)",
                            UpdatedAt = new DateTime(2026, 6, 3, 4, 4, 5, 371, DateTimeKind.Utc).AddTicks(2747)
                        },
                        new
                        {
                            Id = "G002",
                            ColorCode = "#1d4ed8",
                            CreatedAt = new DateTime(2026, 6, 3, 4, 4, 5, 371, DateTimeKind.Utc).AddTicks(2760),
                            Description = "Chi tra, hach toan",
                            Name = "Nhan vien Ke toan",
                            UpdatedAt = new DateTime(2026, 6, 3, 4, 4, 5, 371, DateTimeKind.Utc).AddTicks(2761)
                        });
                });

            modelBuilder.Entity("VietLotApi.Models.RolePermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId", "PermissionCode");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = "G001",
                            PermissionCode = "dashboard"
                        },
                        new
                        {
                            RoleId = "G001",
                            PermissionCode = "phathanh"
                        },
                        new
                        {
                            RoleId = "G001",
                            PermissionCode = "thuhoi"
                        },
                        new
                        {
                            RoleId = "G001",
                            PermissionCode = "trathuong"
                        },
                        new
                        {
                            RoleId = "G001",
                            PermissionCode = "ketoan"
                        },
                        new
                        {
                            RoleId = "G001",
                            PermissionCode = "thamdinh"
                        },
                        new
                        {
                            RoleId = "G001",
                            PermissionCode = "daily"
                        },
                        new
                        {
                            RoleId = "G001",
                            PermissionCode = "baocao"
                        },
                        new
                        {
                            RoleId = "G001",
                            PermissionCode = "hethong"
                        },
                        new
                        {
                            RoleId = "G001",
                            PermissionCode = "nhatky"
                        },
                        new
                        {
                            RoleId = "G001",
                            PermissionCode = "congkhach"
                        },
                        new
                        {
                            RoleId = "G002",
                            PermissionCode = "dashboard"
                        },
                        new
                        {
                            RoleId = "G002",
                            PermissionCode = "ketoan"
                        },
                        new
                        {
                            RoleId = "G002",
                            PermissionCode = "baocao"
                        },
                        new
                        {
                            RoleId = "G002",
                            PermissionCode = "nhatky"
                        });
                });

            modelBuilder.Entity("VietLotApi.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RoleId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VietLotApi.Models.RolePermission", b =>
                {
                    b.HasOne("VietLotApi.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("VietLotApi.Models.User", b =>
                {
                    b.HasOne("VietLotApi.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("VietLotApi.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
